version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DATABASE_URL="postgresql://admin:password@localhost:5432/mydb?schema=public"
    ports:
      - "3005:3005"